### ISSUE TITLE
Graphql do not list the farm public ips

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfchain_graphql#194] opened 2024-10-09 14:55 UTC
![image](https://github.com/user-attachments/assets/e4748d20-0c7c-47df-9d39-a0fcabdd6635)
![image](https://github.com/user-attachments/assets/61fe9395-4a32-48b8-a7d4-5fc2dc9a5ae9)

**Comment by sameh-farouk** [comment] 2024-10-15 14:25
This behavior was explained earlier. The IP address 1.1.1.1 is associated with multiple farms, which is unreasonable. More context can be found here: [GitHub Issue #157](https://github.com/threefoldtech/tfchain_graphql/issues/157).

There was also a fix/workaround implemented in the dashboard to prevent adding an already used IP, but it seems you added this IP before the fix was applied, correct?

**Comment by 0oM4R** [comment] 2024-10-16 11:47
yes this added while ago, but what if i have the address now and the first user added it by mistake or no longer have it, so I will never be able to add it ?

**Comment by sameh-farouk** [comment] 2024-10-17 01:09
Not ideal but yes, as allowing both of you to register same IP would introduce more issues. This was intended as a temporary solution until we can establish a better process and add some verification to the flow. See https://github.com/threefoldtech/tfchain_graphql/issues/157#issuecomment-2108192005 and 
https://github.com/threefoldtech/tfchain_graphql/issues/157#issuecomment-2120902303

I think it is reasonable to close this issue here as GraphQL is not to blame. In fact, Validating to prevent the IP from being registered on multiple farms is a workaround for a higher-level flow issue, which originally allowed this without ensuring the system remains consistent.
However, we can revisit to modify or eliminate this validation here after considering the full image and the implications for other tools to ensure nothing else is adversely affected.

**Closed as not planned** 2024-10-17 09:43 UTC
